using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DatabaseFunctionsGenerator
{
    public class SqlGenerator
    {
        private Database _database;

        public SqlGenerator(Database database)
        {
            _database = database;
        }

        private string GenerateColumnQuery(Column column)
        {
            StringBuilder builder = new StringBuilder();

            builder.Append($"`{column.Name}` ");

            foreach (Table table in _database.Tables)
            {
                //builder.AppendLine(GenerateTableQuery(table));
            }

            builder.Append(column.Type.GetMysqlType());
            builder.Append($"  NOT NULL,");

            return builder.ToString();
        }

        private string GenerateTableQuery(Table table)
        {
            StringBuilder builder = new StringBuilder();
            
            if(!table.HasPrimaryKey)
            {
                Column column;
                ColumnType type;

                type = new ColumnType(Types.Integer, true);     
                column = new Column($"{table.Name}Id", type);

                if ("s" == table.Name.Substring(table.Name.Length - 1, 1))
                {
                    column.Name = $"{table.Name.Substring(0, table.Name.Length - 1)}Id";
                }

                table.Columns.Insert(0, column);
            }

            builder.AppendLine($"CREATE TABLE `{table.Name}` (");

            foreach (Column column in table.Columns)
            {
                builder.AppendLine(GenerateColumnQuery(column));
            }

            builder.AppendLine($") ENGINE=InnoDB DEFAULT CHARSET=latin1;");

            return builder.ToString();
        }

        public string Generate()
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("--generated by database functions generator automatically");
            builder.AppendLine("--for mysql ");
            builder.AppendLine("SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";");
            builder.AppendLine("SET time_zone = \"+00:00\";");

            foreach (Table table in _database.Tables)
            {
                builder.AppendLine(GenerateTableQuery(table));
            }

            return builder.ToString();
        }
    }
}
